# Generated by Django 5.2.9 on 2026-01-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Código único del producto (SKU)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Nombre del producto', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descripción opcional')),
                ('stock', models.IntegerField(default=0, help_text='Cantidad actual en stock')),
                ('is_active', models.BooleanField(default=True, help_text='Producto activo/inactivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
    ]
