# Generated by Django 5.2.9 on 2026-01-02 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_product_description_stockmovement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='reason',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='note',
            field=models.CharField(blank=True, default='', help_text='Notas adicionales (opcional)', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción opcional'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Egreso')], help_text='Tipo de movimiento: IN (ingreso) / OUT (egreso)', max_length=3),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(help_text='Producto afectado por el movimiento', on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='stock.product'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Cantidad del movimiento (debe ser > 0)'),
        ),
    ]
