# Generated by Django 5.2.9 on 2026-01-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stockmovement_updated_at_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Egreso')], help_text='Tipo de movimiento: IN / OUT', max_length=3),
        ),
    ]
