# Generated by Django 5.2.9 on 2026-01-10 22:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo unitario de compra (>= 0). Se usa en Órdenes de Compra.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_cost__gte', 0)), name='stock_product_purchase_cost_non_negative'),
        ),
    ]
