# Generated by Django 5.2.9 on 2026-01-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_product_extended_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Compatibilidad: refleja el estado activo/inactivo.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, help_text='Código único del producto (SKU). Idealmente coincide con el número impreso bajo el código de barras del fabricante.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, help_text='Cantidad actual en stock (no puede ser negativa). Se actualiza por movimientos IN/OUT.'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__gte', 0)), name='stock_product_sale_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0)), name='stock_product_tax_rate_non_negative'),
        ),
    ]
