# Generated by Django 5.2.9 on 2026-01-16 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0008_alter_product_is_active_alter_product_sku_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductLookupCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("BARCODE", "Barcode/SKU")], db_index=True, default="BARCODE", max_length=20)),
                ("query_norm", models.CharField(db_index=True, help_text="Query normalizada (trim; útil para matching).", max_length=64)),
                ("query_raw", models.CharField(blank=True, default="", help_text="Query original recibida.", max_length=64)),
                ("found", models.BooleanField(db_index=True, default=False, help_text="True si se encontró info útil.")),
                ("expires_at", models.DateTimeField(blank=True, db_index=True, help_text="Expiración para NOT_FOUND (anti-spam).", null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("hits", models.PositiveIntegerField(default=0, help_text="Cantidad de veces que se reutilizó desde DB.")),
                ("last_hit_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cache Smart Lookup",
                "verbose_name_plural": "Cache Smart Lookup",
            },
        ),
        migrations.AddConstraint(
            model_name="productlookupcache",
            constraint=models.UniqueConstraint(fields=("kind", "query_norm"), name="uniq_stock_lookup_kind_query"),
        ),
        migrations.AddIndex(
            model_name="productlookupcache",
            index=models.Index(fields=["kind", "query_norm"], name="idx_stock_lookup_kind_query"),
        ),
        migrations.AddIndex(
            model_name="productlookupcache",
            index=models.Index(fields=["found", "expires_at"], name="idx_stock_lookup_found_exp"),
        ),
    ]
