# Generated by Django 5.2.9 on 2026-01-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_productlookupcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen del producto (archivo guardado en MEDIA_ROOT).', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_source_url',
            field=models.URLField(blank=True, default='', help_text='URL de origen de la imagen (si fue descargada/sugerida).'),
        ),
    ]
