# Generated by Django 5.2.9 on 2026-01-06 14:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PAYABLE', 'Payable'), ('RECEIVABLE', 'Receivable')], max_length=12)),
                ('source_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale')], max_length=10)),
                ('source_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PAID', 'Paid')], default='OPEN', max_length=6)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='finance_fin_source__2ed39c_idx'), models.Index(fields=['status'], name='finance_fin_status_0a497e_idx')],
                'constraints': [models.UniqueConstraint(fields=('movement_type', 'source_type', 'source_id'), name='uniq_fin_movement_per_source')],
            },
        ),
    ]
