# Generated by Django 5.2.9 on 2026-01-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialmovement',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PAID', 'Paid'), ('VOID', 'Void')], default='OPEN', max_length=6),
        ),
    ]
