# Generated by Django 5.2.9 on 2026-01-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'ordering': ['role__name', 'permission__code']},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['user__username', 'role__name']},
        ),
    ]
