# Generated by Django 5.2.9 on 2026-01-04 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Orden de Venta', 'verbose_name_plural': 'Órdenes de Venta'},
        ),
        migrations.AlterModelOptions(
            name='salesorderline',
            options={'verbose_name': 'Ítem de Orden de Venta', 'verbose_name_plural': 'Ítems de Órdenes de Venta'},
        ),
    ]
