# Generated by Django 5.2.9 on 2026-01-06 22:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_salesorder_options_and_more'),
        ('stock', '0005_alter_stockmovement_movement_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status', 'created_at'], name='so_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sales_order_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='sales_order_line_unit_price_nonnegative'),
        ),
    ]
