"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# -----------------------
# Helpers
# -----------------------
def _env(*names, default=None):
    """
    Devuelve la primera env var encontrada (en orden).
    """
    for n in names:
        v = os.getenv(n)
        if v not in (None, ""):
            return v
    return default


# SECURITY WARNING: keep the secret key used in production secret!
# ✅ Permite override por env sin romper local (si no está, usa el valor actual)
SECRET_KEY = _env(
    "DJANGO_SECRET_KEY",
    "SECRET_KEY",
    default="django-insecure-ieaiut*)s=m7+10wv^8dbu+5lxnv)hvm_+w!4#j2zlx_1jku6+",
)

# SECURITY WARNING: don't run with debug turned on in production!
# ✅ Permite override por env sin romper local (si no está, queda True como hoy)
DEBUG = str(_env("DJANGO_DEBUG", "DEBUG", default="True")).lower() in ("1", "true", "yes", "y", "on")

# Dev local: permite acceder por 127.0.0.1 / localhost sin errores
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # UI (Frontend ERP)
    "ui",

    # Apps del proyecto
    "security",
    "stock",
    "sales",
    "finance",

    # ✅ IMPORTANTE: usar el AppConfig para que corra el seed en ready()
    "purchases.apps.PurchasesConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",

    # ✅ Restringe /admin/ a superusers
    "config.middleware.AdminSuperuserOnlyMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # ✅ para templates/registration/login.html
        "APP_DIRS": True,  # ✅ incluye templates dentro de apps (ej: ui/templates/)
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "security.context_processors.perm_keys",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# -----------------------
# Database (CI-proof)
# -----------------------
def _db_from_database_url(database_url: str):
    """
    Soporta DATABASE_URL estilo:
    postgres://user:pass@host:5432/dbname
    """
    u = urlparse(database_url)
    if u.scheme not in ("postgres", "postgresql"):
        return None

    name = (u.path or "").lstrip("/") or "erpweb"
    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": name,
        "USER": u.username or "erpuser",
        "PASSWORD": u.password or "",
        "HOST": u.hostname or "127.0.0.1",
        "PORT": str(u.port or 5432),
        "CONN_MAX_AGE": 0,
    }


DATABASE_URL = _env("DATABASE_URL", default=None)
db_from_url = _db_from_database_url(DATABASE_URL) if DATABASE_URL else None

if db_from_url:
    DATABASES = {"default": db_from_url}
else:
    DB_NAME = _env("DB_NAME", "POSTGRES_DB", "PGDATABASE", default="erpweb")
    DB_USER = _env("DB_USER", "POSTGRES_USER", "PGUSER", default="erpuser")
    DB_PASSWORD = _env(
        "DB_PASSWORD",
        "DB_PASS",
        "POSTGRES_PASSWORD",
        "PGPASSWORD",
        default="erpweb123",  # fallback local: tu pass actual
    )
    # IMPORTANTÍSIMO: 127.0.0.1 evita que en CI intente ::1
    DB_HOST = _env("DB_HOST", "POSTGRES_HOST", "PGHOST", default="127.0.0.1")
    DB_PORT = _env("DB_PORT", "POSTGRES_PORT", "PGPORT", default="5432")

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": DB_NAME,
            "USER": DB_USER,
            "PASSWORD": DB_PASSWORD,
            "HOST": DB_HOST,
            "PORT": DB_PORT,
            "CONN_MAX_AGE": 0,
        }
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"

# ✅ Media (uploads): Documentos anexos proveedores (dev)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Auth redirects
# ✅ Ahora el login lleva al Dashboard UI (root "/")
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"
