# config/settings.py
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# -----------------------
# Helpers
# -----------------------
def _env(*names, default=None):
    """
    Devuelve la primera env var encontrada (en orden).
    """
    for n in names:
        v = os.getenv(n)
        if v not in (None, ""):
            return v
    return default


# -----------------------
# Security
# -----------------------
SECRET_KEY = _env(
    "DJANGO_SECRET_KEY",
    "SECRET_KEY",
    default="django-insecure-ieaiut*)s=m7+10wv^8dbu+5lxnv)hvm_+w!4#j2zlx_1jku6+",
)

DEBUG = str(_env("DJANGO_DEBUG", "DEBUG", default="True")).lower() in (
    "1", "true", "yes", "y", "on"
)

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]


# -----------------------
# Application definition
# -----------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # UI (Frontend ERP)
    "ui",

    # Apps del proyecto
    "security",
    "stock",
    "sales",
    "finance",

    # Seed en ready()
    "purchases.apps.PurchasesConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",

    # Admin solo superusers
    "config.middleware.AdminSuperuserOnlyMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"


# -----------------------
# Templates
# -----------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "security.context_processors.perm_keys",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# -----------------------
# Database (CI-proof)
# -----------------------
def _db_from_database_url(database_url: str):
    """
    Soporta DATABASE_URL estilo:
    postgres://user:pass@host:5432/dbname
    """
    u = urlparse(database_url)
    if u.scheme not in ("postgres", "postgresql"):
        return None

    name = (u.path or "").lstrip("/") or "erpweb"
    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": name,
        "USER": u.username or "erpuser",
        "PASSWORD": u.password or "",
        "HOST": u.hostname or "127.0.0.1",
        "PORT": str(u.port or 5432),
        "CONN_MAX_AGE": 0,
    }


DATABASE_URL = _env("DATABASE_URL", default=None)
db_from_url = _db_from_database_url(DATABASE_URL) if DATABASE_URL else None

if db_from_url:
    DATABASES = {"default": db_from_url}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _env("DB_NAME", "POSTGRES_DB", "PGDATABASE", default="erpweb"),
            "USER": _env("DB_USER", "POSTGRES_USER", "PGUSER", default="erpuser"),
            "PASSWORD": _env(
                "DB_PASSWORD",
                "DB_PASS",
                "POSTGRES_PASSWORD",
                "PGPASSWORD",
                default="erpweb123",
            ),
            "HOST": _env("DB_HOST", "POSTGRES_HOST", "PGHOST", default="127.0.0.1"),
            "PORT": _env("DB_PORT", "POSTGRES_PORT", "PGPORT", default="5432"),
            "CONN_MAX_AGE": 0,
        }
    }


# -----------------------
# Cache (safe defaults)
# -----------------------
CACHE_BACKEND = str(
    _env("DJANGO_CACHE_BACKEND", "CACHE_BACKEND", default="locmem")
).lower()

CACHE_TIMEOUT = int(_env("DJANGO_CACHE_TIMEOUT", "CACHE_TIMEOUT", default="3600"))
CACHE_KEY_PREFIX = _env("DJANGO_CACHE_PREFIX", "CACHE_PREFIX", default="erpweb")

if CACHE_BACKEND == "filebased":
    cache_dir = _env("DJANGO_CACHE_DIR", "CACHE_DIR", default=str(BASE_DIR / ".cache"))
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
            "LOCATION": cache_dir,
            "TIMEOUT": CACHE_TIMEOUT,
            "KEY_PREFIX": CACHE_KEY_PREFIX,
            "OPTIONS": {"MAX_ENTRIES": 20000},
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "erpweb-default",
            "TIMEOUT": CACHE_TIMEOUT,
            "KEY_PREFIX": CACHE_KEY_PREFIX,
            "OPTIONS": {"MAX_ENTRIES": 20000},
        }
    }


# -----------------------
# External APIs (Smart Lookup)
# -----------------------
# ⚠️ Estas variables DEBEN existir en settings aunque no haya env vars
# para evitar errores y permitir degradación controlada.

# SerpAPI (Google engine)
SERPAPI_KEY = _env("SERPAPI_KEY", "SERPAPI_API_KEY", default=None)

# OpenAI (extractor/normalizador)
OPENAI_API_KEY = _env("OPENAI_API_KEY", default=None)

# Defaults para Google Search
SMART_LOOKUP_GL = _env("SMART_LOOKUP_GL", default="ar")  # Argentina
SMART_LOOKUP_HL = _env("SMART_LOOKUP_HL", default="es")  # Español

# -----------------------
# ✅ Smart Lookup - Mejoras de calidad (sin romper nada)
# -----------------------
# 1) Marcas conocidas: ayuda a detectar "marca" en el extractor heurístico
#    (se pueden ampliar por cliente/industria sin tocar código)
SMART_LOOKUP_BRANDS_HINTS = [
    # Cuidado personal
    "Algabo",
    "Dove",
    "Rexona",
    "Nivea",
    "Gillette",
    "Pantene",
    "Sedal",
    "Head & Shoulders",

    # Alimentos / bebidas
    "Arcor",
    "Bagley",
    "Terrabusi",
    "Nutella",
    "Ferrero",
    "Coca-Cola",
    "Pepsi",
    "La Serenísima",
    "Sancor",
    "Ilolay",

    # Limpieza
    "Ayudín",
    "Mr. Músculo",
    "Cif",
    "Ala",
    "Skip",
    "Drive",
]

# 2) Dominios confiables: mejora el scoring y reduce ruido
#    (prioriza retailers/fabricantes reales sobre resultados basura)
SMART_LOOKUP_TRUSTED_DOMAINS = [
    # Retail / supermercados
    "carrefour.com.ar",
    "coto.com.ar",
    "jumbo.com.ar",
    "disco.com.ar",
    "vea.com.ar",
    "changomas.com.ar",
    "diaonline.supermercadosdia.com.ar",

    # Farmacias
    "farmacity.com",
    "simply.com.ar",

    # Marketplaces
    "mercadolibre.com.ar",
    "mlstatic.com",

    # Fabricantes
    "algabo.com.ar",
    "arcor.com",
    "ferrero.com",
]


# -----------------------
# Password validation
# -----------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# -----------------------
# Internationalization
# -----------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# -----------------------
# Static & Media
# -----------------------
STATIC_URL = "static/"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# -----------------------
# Auth
# -----------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"
