# Generated by Django 5.2.9 on 2026-01-06 22:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchaseorder_received_at_purchaseorder_received_by_and_more'),
        ('stock', '0005_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='purchase_order_line_unit_cost_nonnegative'),
        ),
    ]
