# Generated by Django 5.2.9 on 2026-01-13 18:14

import django.db.models.deletion
import purchases.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchaseorderline_unit_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=purchases.models._supplier_doc_upload_to)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='address',
            new_name='fiscal_address',
        ),
        migrations.AddField(
            model_name='supplier',
            name='account_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_account_currency',
            field=models.CharField(blank=True, choices=[('ARS', 'Peso (ARS)'), ('USD', 'Dólar (USD)'), ('EUR', 'Euro (EUR)')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_account_holder',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_account_ref',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_account_type',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='supplier',
            name='classification',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_role',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='document_type',
            field=models.CharField(blank=True, choices=[('DNI', 'DNI'), ('LC', 'LC'), ('LE', 'LE'), ('PASAPORTE', 'PASAPORTE'), ('DOC_EXTRANJERO', 'DOC. EXTRANJERO'), ('CUIT', 'CUIT')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email_ap',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='supplier',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='supplier',
            name='fax_or_web',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='supplier',
            name='internal_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_terms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_secondary',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='supplier',
            name='price_list_update_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product_category',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='supplier',
            name='province',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='supplier',
            name='retention_category',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='supplier',
            name='retention_codes',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='supplier',
            name='standard_payment_terms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('BLOCKED', 'Bloqueado')], default='ACTIVE', max_length=12),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('HABITUAL', 'Habitual'), ('OCASIONAL', 'Ocasional')], default='HABITUAL', max_length=12),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_condition',
            field=models.CharField(blank=True, choices=[('RI', 'Responsable Inscripto'), ('MONO', 'Monotributo'), ('EXENTO', 'Exento'), ('NO_RESP', 'No Responsable/No alcanzado'), ('CONS_FINAL', 'Consumidor Final'), ('NO_CAT', 'Sujeto No Categorizado')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='supplier',
            name='trade_name',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='supplier',
            name='transaction_currency',
            field=models.CharField(blank=True, choices=[('ARS', 'Peso (ARS)'), ('USD', 'Dólar (USD)'), ('EUR', 'Euro (EUR)')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='supplier',
            name='vat_condition',
            field=models.CharField(blank=True, choices=[('RI', 'Responsable Inscripto'), ('MONO', 'Monotributo'), ('EXENTO', 'Exento'), ('NO_RESP', 'No Responsable/No alcanzado'), ('CONS_FINAL', 'Consumidor Final'), ('NO_CAT', 'Sujeto No Categorizado')], default='', max_length=16),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['status', 'name'], name='supplier_status_name_idx'),
        ),
        migrations.AddField(
            model_name='supplierdocument',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='purchases.supplier'),
        ),
        migrations.AddField(
            model_name='supplierdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_documents_uploaded', to=settings.AUTH_USER_MODEL),
        ),
    ]
